### ISSUE TITLE
Javascript error in 1.5.8 release

### ISSUE THREAD

**Issue by vitaliitylyk** [JeffDarchuk/SitecoreSidekick#56]
In the latest 1.5.8 release I am getting the following errors in javascript console:

```
main.js:129 Uncaught TypeError: Cannot read property '0' of null
    at main.js:129
```
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?...
    at scsangular.js:7
    at scsangular.js:149
    at m (scsangular.js:11)
    at h (scsangular.js:144)
    at fb (scsangular.js:165)
    at d (scsangular.js:58)
    at zc (scsangular.js:60)
    at Zd (scsangular.js:55)
    at HTMLDocument.<anonymous> (scsangular.js:1276)
    at j (jquery.min.js:2)
```
UI seems to be not functioning properly (it shows "Not Logged In" message) 

![image](https://user-images.githubusercontent.com/4365595/94449995-02a0e180-01ad-11eb-8962-f8d7c362d98b.png)

Could it be related to this change? https://github.com/JeffDarchuk/SitecoreSidekick/commit/990f461a9a2d375b1dc7a473ea024b636628517a#diff-62128033a7c055c30e7914a4d55acaf5

**Comment by JeffDarchuk** [comment]
Hmm, yes.  I did notice that.  However it shouldn't cause that angular exception.  If you click on the angular link, can you give me the details?  The one that starts with `http://errors.angularjs.org/1.4.7/$injector/modulerr?`

**Comment by vitaliitylyk** [comment]
Clicking on the link gives 400 error. Here is the full error message (I have replaced the Sitecore url with `<siteurl>`):

```
https://code.angularjs.org/1.4.7/docs/error/$injector/modulerr?p0=app&p1=Error:[$injector:modulerr]http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=angularUtils.directives.dirPagination&p1=Error: [$injector:nomod] http://errors.angularjs.org/1.4.7/$injector/nomod?p0=angularUtils.directives.dirPagination
    at https://<siteurl>//scs/platform/resources/scsangular.js:7:496
    at https://<siteurl>//scs/platform/resources/scsangular.js:77:233
    at a (https://<siteurl>//scs/platform/resources/scsangular.js:73:48)
    at https://<siteurl>//scs/platform/resources/scsangular.js:75:113
    at https://<siteurl>//scs/platform/resources/scsangular.js:147:19
    at m (https://<siteurl>//scs/platform/resources/scsangular.js:11:276)
    at h (https://<siteurl>//scs/platform/resources/scsangular.js:144:70)
    at https://<siteurl>//scs/platform/resources/scsangular.js:147:39
    at m (https://<siteurl>//scs/platform/resources/scsangular.js:11:276)
    at h (https://<siteurl>//scs/platform/resources/scsangular.js:144:70)athttps://<siteurl>//scs/platform/resources/scsangular.js:7:496athttps://<siteurl>//scs/platform/resources/scsangular.js:149:151atm(https://<siteurl>//scs/platform/resources/scsangular.js:11:276)ath(https://<siteurl>//scs/platform/resources/scsangular.js:144:70)athttps://<siteurl>//scs/platform/resources/scsangular.js:147:39atm(https://<siteurl>//scs/platform/resources/scsangular.js:11:276)ath(https://<siteurl>//scs/platform/resources/scsangular.js:144:70)atfb(https://<siteurl>//scs/platform/resources/scsangular.js:165:9)atd(https://<siteurl>//scs/platform/resources/scsangular.js:58:340)atzc(https://<siteurl>//scs/platform/resources/scsangular.js:60:179
```

**Note:** I did not have that error in 1.5.7 running on the same Sitecore envrironment

**Comment by JeffDarchuk** [comment]
what Sitecore version are you using.  I'm not able to repro on 10 or 9.0.1

**Comment by vitaliitylyk** [comment]
9.3

**Comment by JeffDarchuk** [comment]
I cut a release 1.5.9 which addresses this JS error that on my tests resulted in a benign error message in the consoles but appeared to bring down yours entirely.  Could you please give it a try?

**Comment by vitaliitylyk** [comment]
Works like a charm now, thx!

**Comment by JeffDarchuk** [comment]
perfect, glad to hear it!
