### ISSUE TITLE
Feature request - continue on TemplateMissingFieldException 

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#64]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Rainbow.Storage.Sc.Deserialization.TemplateMissingFieldException: The field 209d3b2f-0daf-4a38-a1a6-3c9f1ee60689 (likely FixLanguageUrls) is not present in Sitecore on the Settings template.
   at Rainbow.Storage.Sc.Deserialization.DefaultDeserializer.Deserialize(IItemData serializedItemData, IFieldValueManipulator fieldValueManipulator)
   at Rainbow.Storage.Sc.SitecoreDataStore.Save(IItemData item, IFieldValueManipulator fieldValueManipulator)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ScsContentMigrator.Services.DatastoreSaver.Save(IDataStore store, IItemData data)
   at ScsContentMigrator.Core.ContentItemInstaller.ProcessItem(PullItemModel args, IItemData localData, IItemData remoteData)
```

In cases like this I would like the option to continue to install the item, but just warn about the missing field instead.

**Comment by JeffDarchuk** [comment]
it may be a possibility, however this functionality is handled by Rainbow entirely.  Without an option within Rainbow to provide this functionality it would be quite difficult to manage, I'll look into it though, thanks for the suggestion.

**Comment by markgibbons25** [comment]
Looks like unicorn handles it as a soft failure: see [here](https://github.com/SitecoreUnicorn/Unicorn/blob/5ba0cc802a116e8fc521b19b08970efb125c94d6/src/Unicorn/Loader/DeserializeFailureRetryer.cs#L164) and [here](https://github.com/SitecoreUnicorn/Rainbow/blob/5abca448a2d50ed23322089f28aa83c1f6c573f5/src/Rainbow.Storage.Sc/Deserialization/DefaultDeserializer.cs#L94).
