### ISSUE TITLE
unable to register action for SCS Editing Context

### ISSUE THREAD

**Issue by markgibbons25** [JeffDarchuk/SitecoreSidekick#66]
Seeing this a fair bit in the CM logs

> 
> 9968 05:55:06 WARN  unable to register action for SCS Editing Context
> Exception: System.NullReferenceException
> Message: Object reference not set to an instance of an object.
> Source: Rainbow.Storage.Sc
>    at Rainbow.Storage.Sc.ItemData.get_DatabaseName()
>    at SitecoreSidekick.ContentTree.ContentTreeNode.Initialize(IItemData item, Boolean open)
>    at ScsEditingContext.TypeContentTreeNode..ctor(IItemData item)
>    at ScsEditingContext.Pipelines.HttpRequestBegin.RegisterEvent.<>c.<Process>b__2_0(IItemData x)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at ScsEditingContext.Pipelines.HttpRequestBegin.RegisterEvent.Process(HttpRequestArgs args)

Would be good to know what causes this and if there is a problem? 
If there's no problem then can we change the log level or disable this warning somehow?

**Comment by JeffDarchuk** [comment]
looking at the stack trace, I'd guess it happens in the rare occurrence of the pipeline running without a valid context database.  It's certainly not a serious problem, but should be taken care of none-the-less.  Thanks for reporting it, i'll make sure the fix is in the next release.
